apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service-deployment
spec:
  replicas: 1 # We can start with 1 replica for the ML service
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/nft-marketplace/ml-service:latest # Placeholder
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service-internal
spec:
  selector:
    app: ml-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP # This service is only accessible from WITHIN the cluster